#服务器
server:
  port: 8080

#数据库
spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    druid:
      url: jdbc:mysql://localhost:3306/bsaeproject
      username: root
      password: root